Raw Loan Analysis
========================
  
## Processing

Download the data, read the data in and save the raw data as an RDA file

```{r loadData,cache=TRUE}
getwd()
download.file("https://spark-public.s3.amazonaws.com/dataanalysis/loansData.csv",destfile="../../data/loansData.csv",method="curl")
dateDownloaded <- date()
dateDownloaded
loansRaw <- read.csv('../../data/loansData.csv')
save(loansRaw,dateDownloaded,file="../../data/loansRaw.rda")
```


### Look at the data set

```{r, dependson="loadData"}
head(loansRaw)
summary(loansRaw)
sapply(loansRaw[1,],class)
```

### Find out about missing values
```{r, dependson="loadData"}
sum(is.na(loansRaw)) 
```

### Find minimum and maximum interest rates
```{r, dependson="loadData"}
rates <- as.numeric(sub("%", "", loansRaw$Interest.Rate))
min(rates)
max(rates)
```

### Find minimum and maximum debts to income ratio
```{r, dependson="loadData"}
ratio <- as.numeric(sub("%", "", loansRaw$Debt.To.Income.Ratio))
min(ratio)
max(ratio)
```

--------------------------

## Exploratory analysis

### Make some univariate plots/summaries


```{r, dependson="loadData"}
hist(rates)
hist(ratio) 
hist(log(loansRaw$Monthly.Income), breaks=50) 
plot(loansRaw$FICO.Range, las=2) 
hist(loansRaw$Amount.Requested)
hist(loansRaw$Amount.Funded.By.Investors)
hist(loansRaw$Open.CREDIT.Lines)
hist(log(loansRaw$Revolving.CREDIT.Balance), breaks=50)
plot(loansRaw$Employment.Length, las=2)
plot(loansRaw$Home.Ownership, las=2) 
```

### Make some univariate tables
```{r, dependson="loadData"}
table(loansRaw$FICO.Range)
table(loansRaw$Interest.Rate)
table(loansRaw$Loan.Length)
table(loansRaw$State)
table(loansRaw$Loan.Purpose)
table(loansRaw$Home.Ownership)
table(loansRaw$Inquiries.in.the.Last.6.Months)
table(loansRaw$Employment.Length)
```

### Plot rate by FICO
```{r, dependson="loadData"}
plot(loansRaw$FICO.Range, rates,pch=19, las=2)
```

Have correlation between FICO and Rate.
Than bigger FICO than less Rate. 
Since FICO is aggregation of other factors, cofounders should be found

### Plot Rate by FICO with color groups for loan lengths 
```{r, dependson="loadData"}
plot(as.numeric(loansRaw$FICO.Range), rates, pch=19, col=loansRaw$Loan.Length)
```
Rates smaller than loan length smaller.

### Plot Rate by Ratio
```{r, dependson="loadData"}
plot(ratio, rates, pch=19, col=loansRaw$Loan.Length)
```
No obvious correlation

### Plot rate by FICO
```{r, dependson="loadData"}
plot(ratio, rates, pch=19, las=2)
```
No obvious correlation

### Plot rate by income
```{r, dependson="loadData"}
plot(log(loansRaw$Monthly.Income), rates, pch=19, las=2, col=loansRaw$Loan.Length)
```
Again no obvious correlation here

### Plot rate by employment length
```{r, dependson="loadData"}
plot(rates, loansRaw$Employment.Length, pch=19, las=2, col=loansRaw$Loan.Length)
```
No correlation here

### Plot rate by credit lines
```{r, dependson="loadData"}
plot(rates, loansRaw$Open.CREDIT.Lines)#, cex=as.numeric(loansRaw$Loan.Length), col=as.numeric(loansRaw$Open.CREDIT.Lines))
```

### Plot rate by purpose
```{r, dependson="loadData"}
plot(loansRaw$Loan.Purpose, rates, las=2)#, cex=as.numeric(loansRaw$Loan.Length), col=as.numeric(loansRaw$Open.CREDIT.Lines))
```
In general car, educational and energy has lower rate, maby because they are short term and then loan length is cofounder here

### Plot rate by purpose
```{r, dependson="loadData"}
plot(as.numeric(loansRaw$Loan.Purpose), rates, col=loansRaw$Loan.Length)#, cex=as.numeric(loansRaw$Loan.Length), col=as.numeric(loansRaw$Open.CREDIT.Lines))

```

### Plot rate by purpose (long teram term)
```{r, dependson="loadData"}
plot(loansRaw$Loan.Purpose[as.numeric(loansRaw$Loan.Length) == 2], rates[as.numeric(loansRaw$Loan.Length) == 2], las=2)#, cex=as.numeric(loansRaw$Loan.Length), col=as.numeric(loansRaw$Open.CREDIT.Lines))
```


### Plot rate by Inquiries.in.the.Last.6.Months 
```{r, dependson="loadData"}
plot(loansRaw$Inquiries.in.the.Last.6.Months, rates)#, cex=as.numeric(loansRaw$Loan.Length), col=as.numeric(loansRaw$Open.CREDIT.Lines))
```
Than more quantity of inquires than more rate (at least it works after 3)


This is evident what main factors which impact rate are FICO and loan length. Loan length in own way is an aggregated value http://en.wikipedia.org/wiki/Credit_score_in_the_United_States.

Now lets try to indentify whats else could affect rate.

------

## Modeling
```
lm1 <- lm(rates ~ as.numeric(loansRaw$FICO.Range) + as.numeric(loansRaw$Loan.Length) + loansRaw$Loan.Purpose)
summary(lm1)

lm2 <- lm(rates ~ as.numeric(loansRaw$FICO.Range) + as.numeric(loansRaw$Loan.Length) + loansRaw$Inquiries.in.the.Last.6.Months + loansRaw$Revolving.CREDIT.Balance)
summary(lm2)

lm3 <- lm(rates ~ as.numeric(loansRaw$FICO.Range) + as.numeric(loansRaw$Loan.Length) + loansRaw$Revolving.CREDIT.Balance) +   loansRaw$Home.Ownership)
summary(lm3)

lm4 <- lm(rates ~ as.numeric(loansRaw$FICO.Range) + as.numeric(loansRaw$Loan.Length) +   loansRaw$Home.Ownership)
summary(lm4)

```
