#lm, confidence interval(inference basic)

#download.file("https://spark-public.s3.amazonaws.com/dataanalysis/movies.txt", "movies.txt", method="curl")
movies <- read.table("movies.txt",sep="\t",header=T,quote="")
head(movies)

par(mfrow=c(1,1))
movies$score <- as.numeric(movies$score)
movies$running_time <- as.numeric(movies$running_time)
movies$box_office <- as.numeric(movies$box_office)
plot(movies$score ~ movies$box_office)
lm1 <- lm(movies$score ~ movies$box_office + movies$running_time)
summary(lm1)
abline(lm1,col="red",lwd=3)
#lines(box,lm1$fitted,col="green",lwd=3)
#confint(lm1,level=0.9)
